[base]
env_name = impulse_wars
checkpoint_interval = 100

[policy]
hidden_size = 512
num_layers = 4

[vec]
total_agents = 4096
num_buffers = 8
num_threads = 24
num_policies = 1

# hist_policy_hidden_size = 512
# hist_policy_num_layers = 4
# hist_policy_percent = 0.25

[selfplay]
enabled = 0
max_size = 100
seed = 42
opp_timeout_steps = 10_000_000
eval_pool_size = 8
eval_games = 0
eval_bot_games = 10240
eval_bots = 1

[bot_eval]
bot_cl_noise = 0

[env]
num_drones = 2
num_agents = 1
map_idx = -1
enable_teams = 0
is_training = 1
bot_policy = 1

bot_cl_noise = 0.75
bot_cl_decay = 0.05

reward_win = 0.3
reward_life = 0.1
reward_kill = 0.1
reward_self_kill = -0.1
reward_energy_emptied = -0.075
reward_weapon_pickup = 0.05
reward_shield_break = 0.05
reward_hit_coef = 0.33

[train]
total_timesteps = 250_000_000
# ent_coef = 0.0001

[sweep]

[sweep.train.total_timesteps]
distribution = log_normal
min = 50_000_000
max = 750_000_000
scale = time

# [sweep.train.ent_coef]
# distribution = log_normal
# min = 0.000001
# max = 0.001
# scale = auto

# [sweep.vec.hist_policy_percent]
# distribution = uniform
# min = 0.0625
# max = 1
# scale = auto
# 
# [sweep.selfplay.opp_timeout_steps]
# distribution = log_normal
# min = 1e6
# max = 1e9
# scale = auto

[sweep.env.bot_cl_noise]
distribution = uniform
min = 0.01
max = 1.0
scale = auto

[sweep.env.bot_cl_decay]
distribution = uniform
min = 0.001
max = 0.5
scale = auto

[sweep.env.reward_win]
distribution = uniform
min = 0.01
max = 0.5
scale = auto

[sweep.env.reward_life]
distribution = uniform
min = 0.0
max = 0.1
scale = auto

[sweep.env.reward_kill]
distribution = uniform
min = 0.0
max = 0.1
scale = auto

[sweep.env.reward_self_kill]
distribution = uniform
min = -0.1
max = 0.0
scale = auto

[sweep.env.reward_energy_emptied]
distribution = uniform
min = -0.1
max = 0.0
scale = auto

[sweep.env.reward_weapon_pickup]
distribution = uniform
min = 0.0
max = 0.1
scale = auto

[sweep.env.reward_shield_break]
distribution = uniform
min = 0.0
max = 0.1
scale = auto

[sweep.env.reward_hit_coef]
distribution = log_normal
min = 0.01
max = 0.5
scale = auto
